In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.reset_option('all')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

C:\Users\Korisnik\AppData\Local\Temp\ipykernel_26984\1481766033.py:1: FutureWarning: data_manager option is deprecated and will be removed in a future version. Only the BlockManager will be available.
  pd.reset_option('all')
C:\Users\Korisnik\AppData\Local\Temp\ipykernel_26984\1481766033.py:1: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.
  pd.reset_option('all')

In [3]:
np_cli_df = pd.read_csv(
    '../data/data_from_db_as_csv/new_polisa_klijent_202603141515.csv',
    low_memory=False,
    dtype={'osig_jmbg': str, 'klijent_id': 'Int64'},
    encoding='utf-8'
)

In [4]:
np_cli_df.columns

Index(['ponuda_id', 'redni_br', 'sif_uloga', 'osig_jmbg', 'osig_svojina',
       'osig_naziv', 'osig_naziv1', 'osig_ulica', 'osig_kuc_br', 'osig_mesto',
       'osig_posta', 'osig_kanton', 'osig_opstina', 'osig_mesto_id',
       'osig_telefon1', 'osig_telefon2', 'osig_mail', 'klijent_id', 'king_id',
       'drzava_id', 'br_pasosa', 'datum_rodjenja', 'pol_id', 'ind_info_ponuda',
       'dat_vozacke', 'sif_delatnost', 'nedef_delatnost', 'sif_bracni_status',
       'mesto_rodj', 'procenat', 'sif_mj'],
      dtype='object')

In [5]:
# np_cli_df.reset_index().head()

In [6]:
np_df = pd.read_csv(
    '../data/data_from_db_as_csv/new_polisa_202603141519.csv', low_memory=False,
    dtype={'ugo_jmbg': str, 'sif_vrsta': 'Int64'},
    encoding='utf-8'
)

In [7]:
np_cli_np_df = pd.merge(
    np_cli_df, np_df, on='ponuda_id', how='inner', suffixes=('_cli', '_np'))

In [8]:
first_columns = ['klijent_id', 'sif_vrsta']
other_columns = [k for k in np_cli_np_df.columns if k not in first_columns]
new_order = first_columns + other_columns
np_cli_np_df = np_cli_np_df[new_order]

In [9]:
(np_cli_np_df['sif_vrsta'] == 0).sum()

np.int64(2688)

In [10]:
np_cli_np_df[np_cli_np_df['sif_vrsta'] == 0].count()

klijent_id                 2567
sif_vrsta                  2688
ponuda_id                  2688
redni_br                   2688
sif_uloga                  2688
osig_jmbg_cli              2660
osig_svojina_cli           2688
osig_naziv_cli             2688
osig_naziv1_cli            1030
osig_ulica_cli             2654
osig_kuc_br_cli            2647
osig_mesto_cli             2625
osig_posta_cli             2632
osig_kanton_cli            2664
osig_opstina_cli           2647
osig_mesto_id_cli          2623
osig_telefon1_cli          1705
osig_telefon2_cli             0
osig_mail_cli               187
king_id_cli                 887
drzava_id                     3
br_pasosa                     3
datum_rodjenja                2
pol_id                     1030
ind_info_ponuda            2688
dat_vozacke                   0
sif_delatnost                 0
nedef_delatnost               0
sif_bracni_status             0
mesto_rodj                    0
procenat                      0
sif_mj                        0
polisa_id                  2688
polisa_no                  2688
broker_id                  2688
sif_org_jed                2688
zamena_polise_no           2687
ind_zamena                 2688
sif_preuzmi                  15
preuzmi_no                 2671
preuzmi_id                 2688
ugo_jmbg                   2623
ugo_svojina                2656
ugo_naziv                  2654
ugo_naziv1                 1071
ugo_ulica                  2614
ugo_kuc_br                 2610
ugo_mesto                  2586
ugo_posta                  2592
ugo_kanton                 2627
ugo_opstina                2609
ugo_mesto_id               2587
ugo_telefon1               1691
ugo_telefon2                  0
ugo_mail                    232
osig_jmbg_np               1178
osig_svojina_np            1185
osig_naziv_np              1178
osig_naziv1_np               46
osig_ulica_np              1176
osig_kuc_br_np             1176
osig_mesto_np              1172
osig_posta_np              1179
osig_kanton_np             1183
osig_opstina_np            1183
osig_mesto_id_np           1179
osig_telefon1_np            441
osig_telefon2_np              0
osig_mail_np                  3
sif_trajanja               2646
dat_od_ug                  2646
dat_do_ug                  2646
dat_od                     2646
dat_do                     2646
time_od                    2646
time_do                    2646
br_dana                    2646
mesto_izdavanja               0
dat_izdavanja              2688
mjesto_izdavanja              0
napomena                     27
napomena_auto                 0
napomena1                     0
p_oper                     2688
p_date                     2688
p_session_id                  0
sif_nac_plac               2530
br_rata                    2530
dat_prve_rate                 6
sif_napomena               2529
premija_ukupno             2688
opis_osiguravac               0
ind_user_skadenca          2644
ind_obracun                   0
suma_osiguranja            2678
polisa_tarifa              2688
veza_polise_no              154
ind_lock_skadenca          2646
miro_polisa_no                0
uw_indikator               2688
ind_uw_kontrola            2688
ugo_isprava                   0
osig_isprava                  0
sif_ikanton                   0
sif_iopstina                  0
ugo_del                       0
king_id_np                    0
sif_datum_dospeca          2530
sif_bankovni_racun         2531
ugo_br_pasosa                 2
osig_br_pasosa                0
konacna_premija            2212
ind_nepravilni_otp_plan      31
ind_dug                    2688
ind_steta                  2688
registarski_broj_polise       0
akcija_id                     0
dtype: int64

In [11]:
# np_cli_np_df.groupby(['klijent_id', 'sif_vrsta']).head()
np_cli_np_df.head()

,klijent_id,sif_vrsta,ponuda_id,redni_br,sif_uloga,osig_jmbg_cli,osig_svojina_cli,osig_naziv_cli,osig_naziv1_cli,osig_ulica_cli,osig_kuc_br_cli,osig_mesto_cli,osig_posta_cli,osig_kanton_cli,osig_opstina_cli,osig_mesto_id_cli,osig_telefon1_cli,osig_telefon2_cli,osig_mail_cli,king_id_cli,drzava_id,br_pasosa,datum_rodjenja,pol_id,ind_info_ponuda,dat_vozacke,sif_delatnost,nedef_delatnost,sif_bracni_status,mesto_rodj,procenat,sif_mj,polisa_id,polisa_no,broker_id,sif_org_jed,zamena_polise_no,ind_zamena,sif_preuzmi,preuzmi_no,preuzmi_id,ugo_jmbg,ugo_svojina,ugo_naziv,ugo_naziv1,ugo_ulica,ugo_kuc_br,ugo_mesto,ugo_posta,ugo_kanton,ugo_opstina,ugo_mesto_id,ugo_telefon1,ugo_telefon2,ugo_mail,osig_jmbg_np,osig_svojina_np,osig_naziv_np,osig_naziv1_np,osig_ulica_np,osig_kuc_br_np,osig_mesto_np,osig_posta_np,osig_kanton_np,osig_opstina_np,osig_mesto_id_np,osig_telefon1_np,osig_telefon2_np,osig_mail_np,sif_trajanja,dat_od_ug,dat_do_ug,dat_od,dat_do,time_od,time_do,br_dana,mesto_izdavanja,dat_izdavanja,mjesto_izdavanja,napomena,napomena_auto,napomena1,p_oper,p_date,p_session_id,sif_nac_plac,br_rata,dat_prve_rate,sif_napomena,premija_ukupno,opis_osiguravac,ind_user_skadenca,ind_obracun,suma_osiguranja,polisa_tarifa,veza_polise_no,ind_lock_skadenca,miro_polisa_no,uw_indikator,ind_uw_kontrola,ugo_isprava,osig_isprava,sif_ikanton,sif_iopstina,ugo_del,king_id_np,sif_datum_dospeca,sif_bankovni_racun,ugo_br_pasosa,osig_br_pasosa,konacna_premija,ind_nepravilni_otp_plan,ind_dug,ind_steta,registarski_broj_polise,akcija_id
0,63,0,153,1,11,4202269430008,2,OKTUM DOO,NaN,VILSONOVO ŠETALIŠTE,6,NOVO SARAJEVO,71120.0,9.0,79.0,1631.0,061111111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,196,187,0.0,N,NaN,0.0,10,4202269430008,2.0,OKTUM DOO,NaN,VILSONOVO ŠETALIŠTE,6,NOVO SARAJEVO,71120.0,9.0,79.0,1631.0,061111111,NaN,NaN,4.200899e+12,2.0,RAIFFEISEN LEASING d.o.o. Sarajevo,NaN,Zmaja od Bosne,bb,Sarajevo Centar,71000.0,9.0,77.0,1600.0,NaN,NaN,NaN,2.0,2024-03-06,2025-03-06,2024-03-06,2025-03-06,23:59,23:59,366.0,NaN,2024-03-06,NaN,NaN,NaN,NaN,9033,2024-03-06,NaN,1.0,1.0,NaN,95.0,1015.26,NaN,N,NaN,82144.9,03.01,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,1015.26,NaN,N,N,NaN,NaN
1,112,0,154,1,12,2409986106483,1,Jelena,Toroman,MIROSLAVA ANTIĆA,BB,Kozarska Dubica,79240.0,99.0,7.0,101.0,NaN,NaN,NaN,500260.0,NaN,NaN,NaN,2.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,79,71,0.0,N,NaN,0.0,10,2409986106483,1.0,Jelena,Toroman,MIROSLAVA ANTIĆA,BB,Kozarska Dubica,79240.0,99.0,7.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2024-03-06,2025-03-06,2024-03-06,2025-03-06,23:59,23:59,366.0,NaN,2024-03-06,NaN,NaN,NaN,NaN,339,2024-03-06,NaN,0.0,1.0,NaN,94.0,1079.99,NaN,N,NaN,35000.0,03.01,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,N,N,NaN,NaN
2,77,0,165,1,12,4236448780005,2,ADRIATIC METALS BH D.O.O. -,NaN,TISOVCI,BB,VAREŠ,71330.0,4.0,96.0,1559.0,NaN,NaN,NaN,701108.0,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,164,196,133509.0,D,NaN,0.0,10,4236448780005,2.0,ADRIATIC METALS BH D.O.O. -,NaN,TISOVCI,BB,VAREŠ,71330.0,4.0,96.0,1559.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2024-03-11,2024-04-30,2024-03-11,2024-04-30,23:59,23:59,51.0,NaN,2024-03-11,NaN,NaN,NaN,NaN,7218,2024-03-07,NaN,0.0,1.0,2024-03-18,94.0,99.62,NaN,N,NaN,23419.0,03.01,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2.0,NaN,NaN,99.62,NaN,N,N,NaN,NaN
3,119,6,166,1,12,4400814960008,2,078 COMMERCE DOO,NaN,MLADENA STOJANOVIĆA,3,Banja Luka,78000.0,99.0,2.0,4.0,000000000,NaN,NaN,701079.0,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3505065,134081,207,582,128650.0,D,NaN,0.0,10,4400814960008,2.0,078 COMMERCE DOO,NaN,MLADENA STOJANOVIĆA,3,Banja Luka,78000.0,99.0,2.0,4.0,000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2024-03-19,2025-03-19,2024-03-19,2025-03-19,23:59,23:59,366.0,NaN,2024-03-07,NaN,NaN,NaN,NaN,7481,2024-03-07,NaN,0.0,1.0,NaN,95.0,499.95,NaN,N,NaN,28190.0,03.01,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,1001793.0,0.0,1.0,NaN,NaN,499.95,NaN,N,N,NaN,NaN
4,127,0,180,1,12,1005987123325,1,ELVEDIN,SALKANOIĆ,Redže Pobrića,BB,ODŽAK,76290.0,2.0,66.0,1367.0,061111111,NaN,NaN,NaN,NaN,NaN,NaN,1.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,158,239,0.0,N,NaN,0.0,10,1005987123325,1.0,ELVEDIN,SALKANOIĆ,Redže Pobrića,BB,ODŽAK,76290.0,2.0,66.0,1367.0,061111111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2024-03-07,2025-03-07,2024-03-07,2025-03-07,23:59,23:59,366.0,NaN,2024-03-07,NaN,NaN,NaN,NaN,9033,2024-03-07,NaN,1.0,1.0,NaN,95.0,4746.94,NaN,N,NaN,156029.0,03.01,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,4746.94,NaN,N,N,NaN,NaN

🧠 1. Šta radi groupby(...).head()
np_cli_np_df.groupby(['klijent_id', 'sif_vrsta']).head()

👉 Ovo znači:

grupiši po (klijent_id, sif_vrsta)
uzmi prvi red iz svake grupe

Zato vidiš normalne podatke.

🧠 2. Šta radi groupby(...).shift(1)
np_cli_np_df.groupby(['klijent_id', 'sif_vrsta']).shift(1)

👉 Ovo znači:
Za SVAKU grupu posebno:

pomjeri redove za 1 unazad
tj. svaki red dobija vrijednosti prethodnog reda iz iste grupe

Aaa kapiram da imaju 2 reda za grupu klijent_id sif_vrsta vrijednosti nebi bile null?

TAKO JE 👏🔥

Sad si ga pogodio 100%.

.expanding()

To znači:

👉 "uzmi sve od početka do trenutnog reda"

Bez ekspanding je samo prosli red a sa expanding je sve do proslog reda, a prosli red je shift(1)

In [12]:
np_cli_np_df.groupby(['klijent_id', 'sif_vrsta']).shift(1).head()

,ponuda_id,redni_br,sif_uloga,osig_jmbg_cli,osig_svojina_cli,osig_naziv_cli,osig_naziv1_cli,osig_ulica_cli,osig_kuc_br_cli,osig_mesto_cli,osig_posta_cli,osig_kanton_cli,osig_opstina_cli,osig_mesto_id_cli,osig_telefon1_cli,osig_telefon2_cli,osig_mail_cli,king_id_cli,drzava_id,br_pasosa,datum_rodjenja,pol_id,ind_info_ponuda,dat_vozacke,sif_delatnost,nedef_delatnost,sif_bracni_status,mesto_rodj,procenat,sif_mj,polisa_id,polisa_no,broker_id,sif_org_jed,zamena_polise_no,ind_zamena,sif_preuzmi,preuzmi_no,preuzmi_id,ugo_jmbg,ugo_svojina,ugo_naziv,ugo_naziv1,ugo_ulica,ugo_kuc_br,ugo_mesto,ugo_posta,ugo_kanton,ugo_opstina,ugo_mesto_id,ugo_telefon1,ugo_telefon2,ugo_mail,osig_jmbg_np,osig_svojina_np,osig_naziv_np,osig_naziv1_np,osig_ulica_np,osig_kuc_br_np,osig_mesto_np,osig_posta_np,osig_kanton_np,osig_opstina_np,osig_mesto_id_np,osig_telefon1_np,osig_telefon2_np,osig_mail_np,sif_trajanja,dat_od_ug,dat_do_ug,dat_od,dat_do,time_od,time_do,br_dana,mesto_izdavanja,dat_izdavanja,mjesto_izdavanja,napomena,napomena_auto,napomena1,p_oper,p_date,p_session_id,sif_nac_plac,br_rata,dat_prve_rate,sif_napomena,premija_ukupno,opis_osiguravac,ind_user_skadenca,ind_obracun,suma_osiguranja,polisa_tarifa,veza_polise_no,ind_lock_skadenca,miro_polisa_no,uw_indikator,ind_uw_kontrola,ugo_isprava,osig_isprava,sif_ikanton,sif_iopstina,ugo_del,king_id_np,sif_datum_dospeca,sif_bankovni_racun,ugo_br_pasosa,osig_br_pasosa,konacna_premija,ind_nepravilni_otp_plan,ind_dug,ind_steta,registarski_broj_polise,akcija_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
print(np_cli_np_df.groupby('klijent_id')['polisa_id'].count().describe())

count    54109.000000
mean         2.109261
std         58.529009
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max      12106.000000
Name: polisa_id, dtype: float64

In [14]:
np_role_df = pd.read_csv(
    '../data/data_from_db_as_csv/new_polisa_uloga_202603172039.csv', low_memory=False)

In [15]:
ugovarac = np_role_df[np_role_df['opis'].str.contains('Ugovarač')]['sif_uloga'].values

In [16]:
jmbg = np_cli_np_df[np_cli_np_df['sif_uloga'].isin(ugovarac)].iloc[10]['osig_jmbg_cli']

In [17]:
np_df[np_df['ugo_jmbg'] == jmbg].head()

,ponuda_id,polisa_id,sif_vrsta,polisa_no,broker_id,sif_org_jed,zamena_polise_no,ind_zamena,sif_preuzmi,preuzmi_no,preuzmi_id,ugo_jmbg,ugo_svojina,ugo_naziv,ugo_naziv1,ugo_ulica,ugo_kuc_br,ugo_mesto,ugo_posta,ugo_kanton,ugo_opstina,ugo_mesto_id,ugo_telefon1,ugo_telefon2,ugo_mail,osig_jmbg,osig_svojina,osig_naziv,osig_naziv1,osig_ulica,osig_kuc_br,osig_mesto,osig_posta,osig_kanton,osig_opstina,osig_mesto_id,osig_telefon1,osig_telefon2,osig_mail,sif_trajanja,dat_od_ug,dat_do_ug,dat_od,dat_do,time_od,time_do,br_dana,mesto_izdavanja,dat_izdavanja,mjesto_izdavanja,napomena,napomena_auto,napomena1,p_oper,p_date,p_session_id,sif_nac_plac,br_rata,dat_prve_rate,sif_napomena,premija_ukupno,opis_osiguravac,ind_user_skadenca,ind_obracun,suma_osiguranja,polisa_tarifa,veza_polise_no,ind_lock_skadenca,miro_polisa_no,uw_indikator,ind_uw_kontrola,ugo_isprava,osig_isprava,sif_ikanton,sif_iopstina,ugo_del,king_id,sif_datum_dospeca,sif_bankovni_racun,ugo_br_pasosa,osig_br_pasosa,konacna_premija,ind_nepravilni_otp_plan,ind_dug,ind_steta,registarski_broj_polise,akcija_id
80,221,3505262,6,134278,17,336,128921.0,D,NaN,0.0,10,2006966198821,1.0,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2024-03-24,2025-03-24,2024-03-24,2025-03-24,23:59,23:59,366.0,NaN,2024-03-19,NaN,NaN,NaN,NaN,8113,2024-03-11,NaN,0.0,1.0,NaN,95.0,909.21,NaN,N,NaN,57577.0,03.01,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,1004601.0,0.0,1.0,NaN,NaN,909.21,NaN,N,N,NaN,NaN
11273,7262,0,13,0,17,336,0.0,N,NaN,NaN,0,2006966198821,1.0,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2025-01-13,2026-01-13,2025-01-13,2026-01-13,23:59,23:59,366.0,NaN,2025-01-10,NaN,NaN,NaN,NaN,8113,2025-01-10,NaN,NaN,NaN,NaN,NaN,0.00,NaN,N,NaN,0.0,NaN,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,N,N,NaN,NaN
11274,7263,3509653,9,6400056,17,336,6110499.0,D,NaN,NaN,0,2006966198821,1.0,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2025-01-13,2026-01-13,2025-01-13,2026-01-13,23:59,23:59,366.0,NaN,2025-01-10,NaN,NaN,NaN,NaN,8113,2025-01-10,NaN,0.0,1.0,NaN,95.0,137.89,NaN,N,NaN,101250.0,09.16,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,1059856.0,0.0,1.0,NaN,NaN,0.00,NaN,N,N,NaN,NaN
15399,11476,3516735,6,139159,17,336,134278.0,D,1.0,NaN,221,2006966198821,1.0,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2025-03-24,2026-03-24,2025-03-24,2026-03-24,23:59,23:59,366.0,NaN,2025-03-10,NaN,NaN,NaN,NaN,8113,2024-03-11,NaN,0.0,1.0,NaN,95.0,865.92,NaN,N,NaN,57577.0,03.01,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,1149077.0,0.0,1.0,NaN,NaN,865.92,NaN,N,N,NaN,NaN
27314,27035,0,22,0,17,336,0.0,N,NaN,NaN,0,2006966198821,1.0,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2025-05-05,2026-05-05,2025-05-05,2026-05-05,23:59,23:59,366.0,NaN,2025-04-30,NaN,NaN,NaN,NaN,8113,2025-04-30,NaN,0.0,1.0,NaN,NaN,42.00,NaN,N,NaN,0.0,18.01,NaN,N,NaN,N,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,0.00,NaN,N,N,NaN,NaN

In [18]:
np_df['sif_vrsta'].unique()

<IntegerArray>
[0, 6, 1, 12, 5, 9, 7, 8, 11, 15, 13, 4, 17, 22, 23]
Length: 15, dtype: Int64

In [19]:
np_df['sif_vrsta'].value_counts()

sif_vrsta
1     24026
15    18323
7     14054
6     13606
0      6836
9      6115
5      6020
8      4661
13     1762
22      998
4       516
17      406
12      221
11      197
23      197
Name: count, dtype: Int64

In [20]:
np_cli_df[np_cli_df['osig_jmbg'] == jmbg].head()

,ponuda_id,redni_br,sif_uloga,osig_jmbg,osig_svojina,osig_naziv,osig_naziv1,osig_ulica,osig_kuc_br,osig_mesto,osig_posta,osig_kanton,osig_opstina,osig_mesto_id,osig_telefon1,osig_telefon2,osig_mail,klijent_id,king_id,drzava_id,br_pasosa,datum_rodjenja,pol_id,ind_info_ponuda,dat_vozacke,sif_delatnost,nedef_delatnost,sif_bracni_status,mesto_rodj,procenat,sif_mj
10,221,1,12,2006966198821,1,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,149,701193.0,NaN,NaN,NaN,2.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13131,27035,1,12,2006966198821,1,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,149,701193.0,NaN,NaN,NaN,2.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13486,7263,1,13,2006966198821,1,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,149,701193.0,NaN,NaN,NaN,2.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13600,7262,1,13,2006966198821,1,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,149,701193.0,NaN,NaN,NaN,2.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17697,11476,1,12,2006966198821,1,ZORA,ILIĆ,DOBOJSKE BRIGADE,BB,Doboj,74000.0,99.0,28.0,39.0,066153768,NaN,NaN,149,701193.0,NaN,NaN,NaN,2.0,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
np_cli_np_df.groupby('osig_jmbg_cli').cumcount()

0             0.0
1             0.0
2             0.0
3             0.0
4             0.0
5             0.0
6             0.0
7             0.0
8             0.0
9             0.0
10            0.0
11            0.0
12            0.0
13            0.0
14            0.0
15            1.0
16            2.0
17            3.0
18            4.0
19            5.0
20            0.0
21            1.0
22            2.0
23            0.0
24            0.0
25            0.0
26            0.0
27            0.0
28            0.0
29            0.0
30            0.0
31            0.0
32            0.0
33            0.0
34            0.0
35            0.0
36            0.0
37            1.0
38            3.0
39            0.0
40            4.0
41            0.0
42            1.0
43            0.0
44            0.0
45            0.0
46            0.0
47            0.0
48            0.0
49            0.0
50            0.0
51            0.0
52            1.0
53            2.0
54            1.0
55            0.0
56            5.0
57            0.0
58            3.0
59            4.0
60            5.0
61            6.0
62            0.0
63            0.0
64            7.0
65            1.0
66            0.0
67            2.0
68            0.0
69            6.0
70            7.0
71            8.0
72            0.0
73            8.0
74            9.0
75           10.0
76            0.0
77            0.0
78            0.0
79            9.0
80            0.0
81            2.0
82            0.0
83            0.0
84            6.0
85            0.0
86            0.0
87            0.0
88            0.0
89            1.0
90            1.0
91            0.0
92            0.0
93            0.0
94           10.0
95           11.0
96           12.0
97            0.0
98           13.0
99           11.0
100           7.0
101          14.0
102           1.0
103           0.0
104          12.0
105           2.0
106          13.0
107           2.0
108          14.0
109           3.0
110           0.0
111           4.0
112          15.0
113          16.0
114          17.0
115          18.0
116          19.0
117          20.0
118           0.0
119           0.0
120          15.0
121           8.0
122           0.0
123           9.0
124           NaN
125          10.0
126           0.0
127           0.0
128           1.0
129           1.0
130           0.0
131           0.0
132           1.0
133           0.0
134          21.0
135          22.0
136          23.0
137           0.0
138          16.0
139           0.0
140          17.0
141           5.0
142           0.0
143           6.0
144           0.0
145          18.0
146           0.0
147           NaN
148           1.0
149           0.0
150           1.0
151           0.0
152           0.0
153           7.0
154          24.0
155          19.0
156           0.0
157          20.0
158           2.0
159           0.0
160           0.0
161          21.0
162           3.0
163           3.0
164           0.0
165           0.0
166           0.0
167          22.0
168          25.0
169          26.0
170           4.0
171          27.0
172           5.0
173           0.0
174          28.0
175          29.0
176           0.0
177           0.0
178           0.0
179          23.0
180           0.0
181          30.0
182           2.0
183          24.0
184          31.0
185           0.0
186          25.0
187          32.0
188           0.0
189           0.0
190           0.0
191          26.0
192           8.0
193           0.0
194           9.0
195           0.0
196           1.0
197           2.0
198           0.0
199          10.0
200          33.0
201          34.0
202          35.0
203          36.0
204           0.0
205           0.0
206           0.0
207           1.0
208           0.0
209           0.0
210           0.0
211           1.0
212           1.0
213          11.0
214           0.0
215          12.0
216           0.0
217          37.0
218          38.0
219          13.0
220           0.0
221          14.0
222           0.0
223          15.0
224          16.0
225          27.0
226           0.0
227           0.0
228          28.0
229           1.0
230           0.0
231           0.0
232           0.0
233           0.0
234           1.0
235           2.0
236          39.0
237           2.0
238           0.0
239          40.0
240          29.0
241           0.0
242           3.0
243           4.0
244           5.0
245           6.0
246           7.0
247           8.0
248           9.0
249           0.0
250           0.0
251           3.0
252           3.0
253          30.0
254           4.0
255           0.0
256           0.0
257           0.0
258          31.0
259           0.0
260           0.0
261           4.0
262           0.0
263           0.0
264           0.0
265           0.0
266           0.0
267           0.0
268           0.0
269          41.0
270          42.0
271           0.0
272          17.0
273           0.0
274           1.0
275          43.0
276           0.0
277           0.0
278           0.0
279           0.0
280           0.0
281          18.0
282           1.0
283           0.0
284           0.0
285           0.0
286           4.0
287           0.0
288           0.0
289           0.0
290           5.0
291           1.0
292           6.0
293           1.0
294           7.0
295           8.0
296          32.0
297           9.0
298           0.0
299          10.0
300          11.0
301           0.0
302           0.0
303          12.0
304           0.0
305          13.0
306           0.0
307          14.0
308           1.0
309           0.0
310          15.0
311          16.0
312           0.0
313           1.0
314           0.0
315           0.0
316           0.0
317          17.0
318          18.0
319           0.0
320           0.0
321           2.0
322           2.0
323           3.0
324           0.0
325           0.0
326           0.0
327           0.0
328           1.0
329           0.0
330           0.0
331           1.0
332          44.0
333          45.0
334          46.0
335          33.0
336           0.0
337           5.0
338           5.0
339           6.0
340           6.0
341           1.0
342           0.0
343           0.0
344          34.0
345          35.0
346           7.0
347           7.0
348           0.0
349           8.0
350           8.0
351          36.0
352           2.0
353           9.0
354           9.0
355          10.0
356          10.0
357          11.0
358           0.0
359           1.0
360           0.0
361           0.0
362           0.0
363          19.0
364           1.0
365           0.0
366           0.0
367           0.0
368          20.0
369          21.0
370           1.0
371          22.0
372          23.0
373          24.0
374          25.0
375          26.0
376          27.0
377          28.0
378          29.0
379           0.0
380           1.0
381           0.0
382          12.0
383           0.0
384           0.0
385           0.0
386          19.0
387           0.0
388          20.0
389           0.0
390           NaN
391          21.0
392           2.0
393          30.0
394          31.0
395           1.0
396          32.0
397           0.0
398           0.0
399          13.0
400          33.0
401          34.0
402           0.0
403           0.0
404           0.0
405           1.0
406          22.0
407           0.0
408           0.0
409          23.0
410           1.0
411          37.0
412           0.0
413           0.0
414           2.0
415           1.0
416           0.0
417           0.0
418           0.0
419          24.0
420           6.0
421          25.0
422           0.0
423           0.0
424          26.0
425          27.0
426           0.0
427           0.0
428           0.0
429           0.0
430           0.0
431           0.0
432           1.0
433           2.0
434           0.0
435           0.0
436          28.0
437           0.0
438          29.0
439           0.0
440          38.0
441           0.0
442           0.0
443           0.0
444           0.0
445           0.0
446           3.0
447           1.0
448           0.0
449          30.0
450           0.0
451           0.0
452           1.0
453           0.0
454           0.0
455           0.0
456           1.0
457           1.0
458           0.0
459           0.0
460           0.0
461           0.0
462           0.0
463           0.0
464           1.0
465           2.0
466           2.0
467           2.0
468           3.0
469          14.0
470           4.0
471           0.0
472           0.0
473           0.0
474           0.0
475           0.0
476           0.0
477           0.0
478          31.0
479           0.0
480           0.0
481           0.0
482           0.0
483           0.0
484           1.0
485           0.0
486          32.0
487           0.0
488           0.0
489           2.0
490           0.0
491           0.0
492           1.0
493           0.0
494          39.0
495          40.0
496          33.0
497           3.0
498           4.0
499           0.0
500           5.0
501           0.0
502           0.0
503           0.0
504          41.0
505           6.0
506          42.0
507           0.0
508           0.0
509           0.0
510           0.0
511           0.0
512           0.0
513           0.0
514           0.0
515           1.0
516          11.0
517           0.0
518           0.0
519           2.0
520           0.0
521           0.0
522           3.0
523           0.0
524          34.0
525           0.0
526          15.0
527           0.0
528           0.0
529          35.0
530          43.0
531           0.0
532           0.0
533           0.0
534           0.0
535          36.0
536           0.0
537          44.0
538           0.0
539          37.0
540           1.0
541          45.0
542           0.0
543           0.0
544           0.0
545           0.0
546           0.0
547           0.0
548           0.0
549           1.0
550           0.0
551           0.0
552          46.0
553           1.0
554          38.0
555           2.0
556          39.0
557           0.0
558           0.0
559           0.0
560           7.0
561           0.0
562           0.0
563           0.0
564           0.0
565           0.0
566          40.0
567           1.0
568          41.0
569           0.0
570          42.0
571           0.0
572          43.0
573           0.0
574           5.0
575           0.0
576           0.0
577           0.0
578          44.0
579           0.0
580           4.0
581           0.0
582           2.0
583           0.0
584          47.0
585          45.0
586          46.0
587           0.0
588          48.0
589           0.0
590           0.0
591           0.0
592          47.0
593           0.0
594          48.0
595          11.0
596          16.0
597           5.0
598          49.0
599          17.0
600          18.0
601           0.0
602           0.0
603          49.0
604           0.0
605           0.0
606           0.0
607           0.0
608           0.0
609           1.0
610          19.0
611           0.0
612           0.0
613          20.0
614           0.0
615          21.0
616           0.0
617           0.0
618           8.0
619           1.0
620           0.0
621           1.0
622           0.0
623          50.0
624           0.0
625          51.0
626           0.0
627           0.0
628          22.0
629           0.0
630           0.0
631           1.0
632           0.0
633           0.0
634           2.0
635           3.0
636           0.0
637          52.0
638           0.0
639           2.0
640           1.0
641          53.0
642           0.0
643           0.0
644           1.0
645           1.0
646           0.0
647           0.0
648           0.0
649           6.0
650           1.0
651           2.0
652           1.0
653           0.0
654          50.0
655           0.0
656          51.0
657           0.0
658           0.0
659           4.0
660           3.0
661           5.0
662           4.0
663           0.0
664          52.0
665           NaN
666           0.0
667           0.0
668           2.0
669           1.0
670           9.0
671           0.0
672           1.0
673           0.0
674           0.0
675          54.0
676           1.0
677           0.0
678           0.0
679           0.0
680           2.0
681           1.0
682           0.0
683           3.0
684           4.0
685           2.0
686          53.0
687           0.0
688          54.0
689           0.0
690           0.0
691           0.0
692           0.0
693           2.0
694           0.0
695           0.0
696           0.0
697           0.0
698           0.0
699           NaN
700           3.0
701          55.0
702           1.0
703           0.0
704          55.0
705          56.0
706           0.0
707           2.0
708           0.0
709           0.0
710           1.0
711           0.0
712           2.0
713           0.0
714           3.0
715          57.0
716           3.0
717           4.0
718           4.0
719           0.0
720           5.0
721           6.0
722           7.0
723           0.0
724           2.0
725           0.0
726          58.0
727           0.0
728           5.0
729           0.0
730           8.0
731           0.0
732          59.0
733           1.0
734           0.0
735           0.0
736           0.0
737           0.0
738           0.0
739           3.0
740           1.0
741           0.0
742          56.0
743           0.0
744           0.0
745          57.0
746           0.0
747           0.0
748           0.0
749          23.0
750          60.0
751           6.0
752           5.0
753           0.0
754           0.0
755          58.0
756           0.0
757           0.0
758           0.0
759           0.0
760          12.0
761           0.0
762           0.0
763           6.0
764           0.0
765           0.0
766           0.0
767           0.0
768           0.0
769           2.0
770           0.0
771          61.0
772           0.0
773           0.0
774           0.0
775          59.0
776           0.0
777           0.0
778           7.0
779           0.0
780           0.0
781           0.0
782           0.0
783           0.0
784           1.0
785           0.0
786           0.0
787           0.0
788           0.0
789           1.0
790           0.0
791          60.0
792          61.0
793           1.0
794           0.0
795          13.0
796           0.0
797           0.0
798          62.0
799           0.0
800           7.0
801          62.0
802           8.0
803           9.0
804          63.0
805          64.0
806           0.0
807           0.0
808           0.0
809           0.0
810           0.0
811           2.0
812           3.0
813           6.0
814          63.0
815           3.0
816           0.0
817           0.0
818           1.0
819           1.0
820           0.0
821           0.0
822          12.0
823          24.0
824           0.0
825           0.0
826           1.0
827           0.0
828          64.0
829           1.0
830          65.0
831           2.0
832           0.0
833          66.0
834           0.0
835          67.0
836           0.0
837          68.0
838           0.0
839           1.0
840           0.0
841           0.0
842           0.0
843           1.0
844           0.0
845           1.0
846           0.0
847          69.0
848           0.0
849           0.0
850           0.0
851           0.0
852           0.0
853           0.0
854          13.0
855          25.0
856           0.0
857           0.0
858           0.0
859           0.0
860           1.0
861          10.0
862          11.0
863          12.0
864           0.0
865           0.0
866          10.0
867          26.0
868          11.0
869          27.0
870          12.0
871           9.0
872           3.0
873          70.0
874          28.0
875           0.0
876           0.0
877          10.0
878           1.0
879          71.0
880           4.0
881          72.0
882           0.0
883           1.0
884          73.0
885           0.0
886           0.0
887           0.0
888           0.0
889           0.0
890           1.0
891           0.0
892          65.0
893          35.0
894           0.0
895           NaN
896           0.0
897          66.0
898          74.0
899           0.0
900          14.0
901          15.0
902           0.0
903          75.0
904          16.0
905          10.0
906           8.0
907           0.0
908           0.0
909           0.0
910           1.0
911           2.0
912          67.0
913           0.0
914           1.0
915           0.0
916           0.0
917           6.0
918           0.0
919          76.0
920           0.0
921          17.0
922           3.0
923           1.0
924          47.0
925           0.0
926           1.0
927          77.0
928           0.0
929           0.0
930          78.0
931           0.0
932           1.0
933          79.0
934          80.0
935           1.0
936          14.0
937          18.0
938          19.0
939          20.0
940           2.0
941           0.0
942          81.0
943           4.0
944           0.0
945          29.0
946           0.0
947           0.0
948           7.0
949           1.0
950           0.0
951           4.0
952           0.0
953           0.0
954          82.0
955          21.0
956           0.0
957          83.0
958          84.0
959           0.0
960           0.0
961          85.0
962          30.0
963           1.0
964           0.0
965           1.0
966           0.0
967           0.0
968          68.0
969           0.0
970          86.0
971           0.0
972          87.0
973           0.0
974          88.0
975           0.0
976           1.0
977           0.0
978           2.0
979           3.0
980           1.0
981           0.0
982           0.0
983           0.0
984           1.0
985           NaN
986           7.0
987           0.0
988          89.0
989           1.0
990           0.0
991          90.0
992          91.0
993          15.0
994          31.0
995           1.0
996          69.0
997          16.0
998          17.0
999          13.0
1000         18.0
1001         32.0
1002          1.0
1003          0.0
1004          1.0
1005          0.0
1006          0.0
1007          0.0
1008         92.0
1009          1.0
1010         70.0
1011          1.0
1012          7.0
1013          0.0
1014          5.0
1015          5.0
1016          0.0
1017          0.0
1018         71.0
1019          0.0
1020          0.0
1021          0.0
1022         72.0
1023          0.0
1024          0.0
1025          0.0
1026          0.0
1027         93.0
1028          0.0
1029          1.0
1030          0.0
1031          0.0
1032          1.0
1033         33.0
1034          0.0
1035         14.0
1036          0.0
1037         94.0
1038          0.0
1039          1.0
1040          2.0
1041          0.0
1042          0.0
1043         73.0
1044          0.0
1045          0.0
1046          0.0
1047          0.0
1048          0.0
1049          3.0
1050         34.0
1051          0.0
1052          4.0
1053         74.0
1054          1.0
1055          NaN
1056          0.0
1057          0.0
1058         75.0
1059          0.0
1060          0.0
1061         11.0
1062         95.0
1063          0.0
1064          0.0
1065         13.0
1066          0.0
1067          0.0
1068          0.0
1069          0.0
1070         76.0
1071          0.0
1072          0.0
1073          0.0
1074          4.0
1075          0.0
1076         96.0
1077          0.0
1078         97.0
1079          0.0
1080         98.0
1081          0.0
1082          0.0
1083          1.0
1084         77.0
1085          2.0
1086         99.0
1087          0.0
1088          0.0
1089          0.0
1090          1.0
1091          0.0
1092          0.0
1093          0.0
1094          2.0
1095          0.0
1096          0.0
1097          0.0
1098          NaN
1099          0.0
1100          0.0
1101         35.0
1102          0.0
1103          1.0
1104        100.0
1105          0.0
1106          5.0
1107         78.0
1108          6.0
1109          6.0
1110          0.0

In [22]:
len(np_cli_df)

114343

In [23]:
np_cli_df['osig_jmbg'].nunique()

53728